export const btn: string
export const btnDark: string
export const btnIcon: string
export const btnLight: string
export const btnLighter: string
export const container: string
export const content: string
export const disableScroll: string
export const next: string
export const sectionTitle: string
export const srOnly: string
export const tooltipOverwrite: string
