export const left: string
export const reverse: string
export const right: string
export const timeline: string
export const timelineItem: string
export const timelineItemBody: string
export const timelineItemHeader: string
export const timelineLink: string
export const timelineSection: string
export const viewOlderBtn: string
