import { Talk } from '../../../../libs/shared/types/profile'

export const talks: Talk[] = [
  {
    text: 'slides.calendar_app_workshop_in_flutter_japan_user_group_2022',
    host: 'Flutter Japan User Group',
    url: 'https://docs.google.com/presentation/d/141tABAoz2LYozHC89fSwqqXJtGEX47mVXyJ5SEfYtZY/edit?usp=sharing',
    youtubeUrl: 'https://www.youtube.com/watch?v=dlAKk1VAQyA',
    place: 'YouTube',
    date: '2022/07/02',
    enabled: true,
  },
  {
    text: 'slides.oss_activities_2022',
    host: 'me',
    url: 'https://docs.google.com/presentation/d/141tABAoz2LYozHC89fSwqqXJtGEX47mVXyJ5SEfYtZY/edit?usp=sharing',
    youtubeUrl: null,
    place: 'EventIn',
    date: '2022/06/23',
    enabled: true,
  },
  {
    text: 'slides.about_22s_googleio_wwdc_recap',
    host: 'PWA Night',
    url: 'https://webneko.dev/posts/22s-googleio-wwdc-recap',
    youtubeUrl: null,
    place: 'Zoom',
    date: '2022/06/15',
    enabled: true,
  },
  {
    text: 'slides.customize_markuplint',
    host: 'me',
    url: 'https://docs.google.com/presentation/d/1IGtF7dFfB4QTHNPBDND8KeczHRSrs0Uy7eBMvYqYHdQ/edit?usp=sharing',
    youtubeUrl: null,
    place: 'EventIn',
    date: '2022/04/21',
    enabled: true,
  },
  {
    text: 'slides.setup_markuplint',
    host: 'me',
    url: 'https://docs.google.com/presentation/d/1vvkYKVMRt6pYJSZC2Fm_eFKYxjhrqchfqn6UJBKikfU/edit?usp=sharing',
    youtubeUrl: null,
    place: 'EventIn',
    date: '2022/04/14',
    enabled: true,
  },
  {
    text: 'slides.learn_accessibility_again',
    host: 'me',
    url: 'https://docs.google.com/presentation/d/1TGXqz-mg1mkKPRazb_jT5umxC98h6dXrhQqdJX4YJUE/edit?usp=sharing',
    youtubeUrl: null,
    place: 'EventIn',
    date: '2022/03/10',
    enabled: true,
  },
  {
    text: 'slides.react_workshop_in_line_developer_community_2022',
    host: 'LINE Developer Community',
    url: 'https://webneko.dev/posts/the-answer-to-learn-react-with-line',
    youtubeUrl: 'https://www.youtube.com/watch?v=D8GeQyrueEY',
    place: 'YouTube',
    date: '2022/03/03',
    enabled: true,
  },
  {
    text: 'slides.learn_accessibility',
    host: 'me',
    url: 'https://docs.google.com/presentation/d/1z6OFNh3NnN9mP3Rh2wGhyOpy_QslKcZfR6I8K7blOEY/edit?usp=sharing',
    youtubeUrl: null,
    place: 'EventIn',
    date: '2022/01/20',
    enabled: true,
  },
  {
    text: 'slides.inside_the_website_in_vscodecon_jp_2021',
    host: 'VS Code Meetup',
    url: 'https://webneko.dev/posts/inside-the-website-in-vscodecon-jp-2021',
    youtubeUrl: 'https://www.youtube.com/watch?v=Y8dl1y2qdG8',
    place: 'YouTube',
    date: '2021/11/01',
    enabled: true,
  },
  {
    text: 'slides.github_issues_usage_as_a_cmd',
    host: 'microCMS',
    url: 'https://webneko.dev/posts/github-issues-usage-as-a-cms',
    youtubeUrl: 'https://www.youtube.com/watch?v=qCPqheDPq6g',
    place: 'YouTube',
    date: '2021/10/28',
    enabled: true,
  },
  {
    text: 'slides.recommend_to_developers_relations_in_community_handson',
    host: 'DevRel Meetup Tokyo',
    url: 'https://webneko.dev/posts/challenge-the-community-handson-2021',
    youtubeUrl: 'https://www.youtube.com/watch?v=oUCGt-SNmfE',
    place: 'YouTube',
    date: '2021/04/12',
    enabled: true,
  },
  {
    text: 'slides.personal_sponsor_in_jaws_days_2021',
    host: 'JAWS UG',
    url: 'https://jawsdays2021.jaws-ug.jp/individual-supporter/#016',
    youtubeUrl: null,
    place: 'YouTube',
    date: '2021/03/21',
    enabled: true,
  },
  {
    text: 'slides.the_world_revolves_around_slack',
    host: 'VR Study',
    url: 'https://webneko.dev/posts/recommend-tools-in-vr-study-3',
    youtubeUrl: 'https://www.youtube.com/watch?v=l3BCTi3xSds',
    place: 'YouTube',
    date: '2020/06/21',
    enabled: true,
  },
  {
    text: 'slides.pwa_that_was_closer_to_me',
    host: 'PWA Night',
    url: 'https://webneko.dev/posts/more-closer-pwa-2020',
    youtubeUrl: 'https://www.youtube.com/watch?v=Phsf7hjQkAI',
    place: 'YouTube',
    date: '2020/05/20',
    enabled: true,
  },
  {
    text: 'slides.practical_use_of_transition',
    host: 'Yumemi inc.',
    url: 'https://webneko.dev/posts/vue-transition-more-pratically',
    youtubeUrl: null,
    place: 'Yumemi inc.',
    date: '2020/01/23',
    enabled: true,
  },
  {
    text: 'slides.the_point_of_composition_api',
    host: 'v-okinawa',
    url: 'https://webneko.dev/posts/notices-of-composition-api-in-vue3-eve',
    youtubeUrl: null,
    place: 'Zoom',
    date: '2019/12/16',
    enabled: true,
  },
  {
    text: 'slides.looking_back_in_2019',
    host: 'v-kansai',
    url: 'https://webneko.dev/posts/feedback-2019',
    youtubeUrl: null,
    place: 'Moneyforward',
    date: '2019/12/06',
    enabled: true,
  },
  {
    text: 'slides.vue_cli_test_tips',
    host: 'necco inc.',
    url: 'https://slides.com/jiyuujin/20190817',
    youtubeUrl: null,
    place: 'necco inc.',
    date: '2019/08/17',
    enabled: true,
  },
]
