export const hamburger: string
export const hamburgerContainer: string
export const hamburgerItem: string
export const nav: string
export const navActive: string
export const navContainer: string
export const navContent: string
export const navHidden: string
export const navIcon: string
export const navLink: string
export const navLinks: string
