name: Deploy to S3

on:
  push:
    branches:
      - main
  #  pull_request:
  #    branches:
  #      - main

jobs:
  deploy:
    name: deploy

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # - uses: nrwl/nx-set-shas@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Install Dependencies
        run: |
          npm i serverless@2.11 -g
          yarn

      - name: Company (Legacy) Transpile
        run: |
          yarn nx run company-legacyapp:css
          yarn nx run company-legacyapp:build
          yarn nx run company-legacyapp:export
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - shell: bash
        run: |
          touch apps/portfolio-legacyapp/.env
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env
          echo "LHCI_GITHUB_APP_TOKEN=${{ secrets.LHCI_GITHUB_APP_TOKEN }}" >> .env
          echo "CTF_BLOG_POST_TYPE_ID=${{ secrets.CTF_BLOG_POST_TYPE_ID }}" >> .env
          echo "CTF_SPACE_ID=${{ secrets.CTF_SPACE_ID }}" >> .env
          echo "CTF_CDA_ACCESS_TOKEN=${{ secrets.CTF_CDA_ACCESS_TOKEN }}" >> .env

      - name: Portfolio (Legacy) Transpile
        run: |
          yarn nx run portfolio-legacyapp:css
          yarn nx run portfolio-legacyapp:build
          yarn nx run portfolio-legacyapp:export
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NEXT_PUBLIC_LIVE_LAMBDA_ENDPOINT: ${{ secrets.NEXT_PUBLIC_LIVE_LAMBDA_ENDPOINT }}
          NEXT_PUBLIC_LIVE_STRIPE_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_LIVE_STRIPE_PUBLIC_KEY }}
          NEXT_PUBLIC_TEST_STRIPE_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_TEST_STRIPE_PUBLIC_KEY }}
          NEXT_PUBLIC_LHCI_GITHUB_APP_TOKEN: ${{ secrets.NEXT_PUBLIC_LHCI_GITHUB_APP_TOKEN }}

      # - name: Deploy Payment to Lambda (v2)
      #   run: |
      #     cd apps/payment-api-v2/
      #     yarn deploy
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     NEXT_LIVE_STRIPE_PUBLIC_KEY: ${{ secrets.NEXT_LIVE_STRIPE_PUBLIC_KEY }}
      #     NEXT_LIVE_STRIPE_SECRET_KEY: ${{ secrets.NEXT_LIVE_STRIPE_SECRET_KEY }}
      #     NEXT_LIVE_LAMBDA_ENDPOINT: ${{ secrets.NEXT_LIVE_LAMBDA_ENDPOINT }}

      # - name: Deploy Payment to Lambda (v1)
      #   run: |
      #     cd apps/payment-api/
      #     tsc lib/checkout.ts
      #     yarn payment-api:deploy
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     NEXT_LIVE_STRIPE_PUBLIC_KEY: ${{ secrets.NEXT_LIVE_STRIPE_PUBLIC_KEY }}
      #     NEXT_LIVE_STRIPE_SECRET_KEY: ${{ secrets.NEXT_LIVE_STRIPE_SECRET_KEY }}
      #     NEXT_LIVE_LAMBDA_ENDPOINT: ${{ secrets.NEXT_LIVE_LAMBDA_ENDPOINT }}

      - name: Deploy Company (Legacy) to S3
        run: bash scripts/sub_company_legacy_directory.sh

      # - name: Deploy Portfolio to S3
      #   run: bash scripts/sub_portfolio_directory.sh

      - name: Deploy Portfolio (Legacy) to S3
        run: bash scripts/sub_portfolio_legacy_directory.sh
